###################################################################

# Created by write_sdc on Sat May 23 16:01:50 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_wire_load_model -name Small -library                                       \
sc9_cln40g_base_rvt_tt_typical_max_0p90v_25c
set_load -pin_load 0.05 [get_ports {out_result[7]}]
set_load -pin_load 0.05 [get_ports {out_result[6]}]
set_load -pin_load 0.05 [get_ports {out_result[5]}]
set_load -pin_load 0.05 [get_ports {out_result[4]}]
set_load -pin_load 0.05 [get_ports {out_result[3]}]
set_load -pin_load 0.05 [get_ports {out_result[2]}]
set_load -pin_load 0.05 [get_ports {out_result[1]}]
set_load -pin_load 0.05 [get_ports {out_result[0]}]
set_max_capacitance 0.15 [get_ports clk]
set_max_capacitance 0.15 [get_ports rst_n]
set_max_capacitance 0.15 [get_ports {in_a[7]}]
set_max_capacitance 0.15 [get_ports {in_a[6]}]
set_max_capacitance 0.15 [get_ports {in_a[5]}]
set_max_capacitance 0.15 [get_ports {in_a[4]}]
set_max_capacitance 0.15 [get_ports {in_a[3]}]
set_max_capacitance 0.15 [get_ports {in_a[2]}]
set_max_capacitance 0.15 [get_ports {in_a[1]}]
set_max_capacitance 0.15 [get_ports {in_a[0]}]
set_max_capacitance 0.15 [get_ports {in_b[7]}]
set_max_capacitance 0.15 [get_ports {in_b[6]}]
set_max_capacitance 0.15 [get_ports {in_b[5]}]
set_max_capacitance 0.15 [get_ports {in_b[4]}]
set_max_capacitance 0.15 [get_ports {in_b[3]}]
set_max_capacitance 0.15 [get_ports {in_b[2]}]
set_max_capacitance 0.15 [get_ports {in_b[1]}]
set_max_capacitance 0.15 [get_ports {in_b[0]}]
set_max_capacitance 0.15 [get_ports acc_clear]
set_max_fanout 10 [get_ports clk]
set_max_fanout 10 [get_ports rst_n]
set_max_fanout 10 [get_ports {in_a[7]}]
set_max_fanout 10 [get_ports {in_a[6]}]
set_max_fanout 10 [get_ports {in_a[5]}]
set_max_fanout 10 [get_ports {in_a[4]}]
set_max_fanout 10 [get_ports {in_a[3]}]
set_max_fanout 10 [get_ports {in_a[2]}]
set_max_fanout 10 [get_ports {in_a[1]}]
set_max_fanout 10 [get_ports {in_a[0]}]
set_max_fanout 10 [get_ports {in_b[7]}]
set_max_fanout 10 [get_ports {in_b[6]}]
set_max_fanout 10 [get_ports {in_b[5]}]
set_max_fanout 10 [get_ports {in_b[4]}]
set_max_fanout 10 [get_ports {in_b[3]}]
set_max_fanout 10 [get_ports {in_b[2]}]
set_max_fanout 10 [get_ports {in_b[1]}]
set_max_fanout 10 [get_ports {in_b[0]}]
set_max_fanout 10 [get_ports acc_clear]
set_max_transition 3 [get_ports clk]
set_max_transition 3 [get_ports rst_n]
set_max_transition 3 [get_ports {in_a[7]}]
set_max_transition 3 [get_ports {in_a[6]}]
set_max_transition 3 [get_ports {in_a[5]}]
set_max_transition 3 [get_ports {in_a[4]}]
set_max_transition 3 [get_ports {in_a[3]}]
set_max_transition 3 [get_ports {in_a[2]}]
set_max_transition 3 [get_ports {in_a[1]}]
set_max_transition 3 [get_ports {in_a[0]}]
set_max_transition 3 [get_ports {in_b[7]}]
set_max_transition 3 [get_ports {in_b[6]}]
set_max_transition 3 [get_ports {in_b[5]}]
set_max_transition 3 [get_ports {in_b[4]}]
set_max_transition 3 [get_ports {in_b[3]}]
set_max_transition 3 [get_ports {in_b[2]}]
set_max_transition 3 [get_ports {in_b[1]}]
set_max_transition 3 [get_ports {in_b[0]}]
set_max_transition 3 [get_ports acc_clear]
create_clock [get_ports clk]  -period 10  -waveform {0 5}
set_clock_uncertainty 0.1  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  -max 1  [get_ports {in_a[7]}]
set_input_delay -clock clk  -min 0  [get_ports {in_a[7]}]
set_input_delay -clock clk  -max 1  [get_ports {in_a[6]}]
set_input_delay -clock clk  -min 0  [get_ports {in_a[6]}]
set_input_delay -clock clk  -max 1  [get_ports {in_a[5]}]
set_input_delay -clock clk  -min 0  [get_ports {in_a[5]}]
set_input_delay -clock clk  -max 1  [get_ports {in_a[4]}]
set_input_delay -clock clk  -min 0  [get_ports {in_a[4]}]
set_input_delay -clock clk  -max 1  [get_ports {in_a[3]}]
set_input_delay -clock clk  -min 0  [get_ports {in_a[3]}]
set_input_delay -clock clk  -max 1  [get_ports {in_a[2]}]
set_input_delay -clock clk  -min 0  [get_ports {in_a[2]}]
set_input_delay -clock clk  -max 1  [get_ports {in_a[1]}]
set_input_delay -clock clk  -min 0  [get_ports {in_a[1]}]
set_input_delay -clock clk  -max 1  [get_ports {in_a[0]}]
set_input_delay -clock clk  -min 0  [get_ports {in_a[0]}]
set_input_delay -clock clk  -max 1  [get_ports {in_b[7]}]
set_input_delay -clock clk  -min 0  [get_ports {in_b[7]}]
set_input_delay -clock clk  -max 1  [get_ports {in_b[6]}]
set_input_delay -clock clk  -min 0  [get_ports {in_b[6]}]
set_input_delay -clock clk  -max 1  [get_ports {in_b[5]}]
set_input_delay -clock clk  -min 0  [get_ports {in_b[5]}]
set_input_delay -clock clk  -max 1  [get_ports {in_b[4]}]
set_input_delay -clock clk  -min 0  [get_ports {in_b[4]}]
set_input_delay -clock clk  -max 1  [get_ports {in_b[3]}]
set_input_delay -clock clk  -min 0  [get_ports {in_b[3]}]
set_input_delay -clock clk  -max 1  [get_ports {in_b[2]}]
set_input_delay -clock clk  -min 0  [get_ports {in_b[2]}]
set_input_delay -clock clk  -max 1  [get_ports {in_b[1]}]
set_input_delay -clock clk  -min 0  [get_ports {in_b[1]}]
set_input_delay -clock clk  -max 1  [get_ports {in_b[0]}]
set_input_delay -clock clk  -min 0  [get_ports {in_b[0]}]
set_input_delay -clock clk  -max 1  [get_ports acc_clear]
set_input_delay -clock clk  -min 0  [get_ports acc_clear]
set_output_delay -clock clk  -max 1  [get_ports {out_result[7]}]
set_output_delay -clock clk  -min 0  [get_ports {out_result[7]}]
set_output_delay -clock clk  -max 1  [get_ports {out_result[6]}]
set_output_delay -clock clk  -min 0  [get_ports {out_result[6]}]
set_output_delay -clock clk  -max 1  [get_ports {out_result[5]}]
set_output_delay -clock clk  -min 0  [get_ports {out_result[5]}]
set_output_delay -clock clk  -max 1  [get_ports {out_result[4]}]
set_output_delay -clock clk  -min 0  [get_ports {out_result[4]}]
set_output_delay -clock clk  -max 1  [get_ports {out_result[3]}]
set_output_delay -clock clk  -min 0  [get_ports {out_result[3]}]
set_output_delay -clock clk  -max 1  [get_ports {out_result[2]}]
set_output_delay -clock clk  -min 0  [get_ports {out_result[2]}]
set_output_delay -clock clk  -max 1  [get_ports {out_result[1]}]
set_output_delay -clock clk  -min 0  [get_ports {out_result[1]}]
set_output_delay -clock clk  -max 1  [get_ports {out_result[0]}]
set_output_delay -clock clk  -min 0  [get_ports {out_result[0]}]
set_input_transition -max 0.5  [get_ports clk]
set_input_transition -min 0.5  [get_ports clk]
set_input_transition -max 0.5  [get_ports rst_n]
set_input_transition -min 0.5  [get_ports rst_n]
set_input_transition -max 0.5  [get_ports {in_a[7]}]
set_input_transition -min 0.5  [get_ports {in_a[7]}]
set_input_transition -max 0.5  [get_ports {in_a[6]}]
set_input_transition -min 0.5  [get_ports {in_a[6]}]
set_input_transition -max 0.5  [get_ports {in_a[5]}]
set_input_transition -min 0.5  [get_ports {in_a[5]}]
set_input_transition -max 0.5  [get_ports {in_a[4]}]
set_input_transition -min 0.5  [get_ports {in_a[4]}]
set_input_transition -max 0.5  [get_ports {in_a[3]}]
set_input_transition -min 0.5  [get_ports {in_a[3]}]
set_input_transition -max 0.5  [get_ports {in_a[2]}]
set_input_transition -min 0.5  [get_ports {in_a[2]}]
set_input_transition -max 0.5  [get_ports {in_a[1]}]
set_input_transition -min 0.5  [get_ports {in_a[1]}]
set_input_transition -max 0.5  [get_ports {in_a[0]}]
set_input_transition -min 0.5  [get_ports {in_a[0]}]
set_input_transition -max 0.5  [get_ports {in_b[7]}]
set_input_transition -min 0.5  [get_ports {in_b[7]}]
set_input_transition -max 0.5  [get_ports {in_b[6]}]
set_input_transition -min 0.5  [get_ports {in_b[6]}]
set_input_transition -max 0.5  [get_ports {in_b[5]}]
set_input_transition -min 0.5  [get_ports {in_b[5]}]
set_input_transition -max 0.5  [get_ports {in_b[4]}]
set_input_transition -min 0.5  [get_ports {in_b[4]}]
set_input_transition -max 0.5  [get_ports {in_b[3]}]
set_input_transition -min 0.5  [get_ports {in_b[3]}]
set_input_transition -max 0.5  [get_ports {in_b[2]}]
set_input_transition -min 0.5  [get_ports {in_b[2]}]
set_input_transition -max 0.5  [get_ports {in_b[1]}]
set_input_transition -min 0.5  [get_ports {in_b[1]}]
set_input_transition -max 0.5  [get_ports {in_b[0]}]
set_input_transition -min 0.5  [get_ports {in_b[0]}]
set_input_transition -max 0.5  [get_ports acc_clear]
set_input_transition -min 0.5  [get_ports acc_clear]
