###################################################################

# Created by write_sdc on Sat May 23 16:18:13 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_wire_load_model -name Small -library                                       \
sc9_cln40g_base_rvt_tt_typical_max_0p90v_25c
set_load -pin_load 0.05 [get_ports sign_prod]
set_load -pin_load 0.05 [get_ports {exp_prod_base4[5]}]
set_load -pin_load 0.05 [get_ports {exp_prod_base4[4]}]
set_load -pin_load 0.05 [get_ports {exp_prod_base4[3]}]
set_load -pin_load 0.05 [get_ports {exp_prod_base4[2]}]
set_load -pin_load 0.05 [get_ports {exp_prod_base4[1]}]
set_load -pin_load 0.05 [get_ports {exp_prod_base4[0]}]
set_load -pin_load 0.05 [get_ports {man_prod[5]}]
set_load -pin_load 0.05 [get_ports {man_prod[4]}]
set_load -pin_load 0.05 [get_ports {man_prod[3]}]
set_load -pin_load 0.05 [get_ports {man_prod[2]}]
set_load -pin_load 0.05 [get_ports {man_prod[1]}]
set_load -pin_load 0.05 [get_ports {man_prod[0]}]
set_max_capacitance 0.15 [get_ports sign_a]
set_max_capacitance 0.15 [get_ports {exp_a[3]}]
set_max_capacitance 0.15 [get_ports {exp_a[2]}]
set_max_capacitance 0.15 [get_ports {exp_a[1]}]
set_max_capacitance 0.15 [get_ports {exp_a[0]}]
set_max_capacitance 0.15 [get_ports {man_a[2]}]
set_max_capacitance 0.15 [get_ports {man_a[1]}]
set_max_capacitance 0.15 [get_ports {man_a[0]}]
set_max_capacitance 0.15 [get_ports sign_w]
set_max_capacitance 0.15 [get_ports {exp_w[3]}]
set_max_capacitance 0.15 [get_ports {exp_w[2]}]
set_max_capacitance 0.15 [get_ports {exp_w[1]}]
set_max_capacitance 0.15 [get_ports {exp_w[0]}]
set_max_capacitance 0.15 [get_ports {man_w[2]}]
set_max_capacitance 0.15 [get_ports {man_w[1]}]
set_max_capacitance 0.15 [get_ports {man_w[0]}]
set_max_fanout 10 [get_ports sign_a]
set_max_fanout 10 [get_ports {exp_a[3]}]
set_max_fanout 10 [get_ports {exp_a[2]}]
set_max_fanout 10 [get_ports {exp_a[1]}]
set_max_fanout 10 [get_ports {exp_a[0]}]
set_max_fanout 10 [get_ports {man_a[2]}]
set_max_fanout 10 [get_ports {man_a[1]}]
set_max_fanout 10 [get_ports {man_a[0]}]
set_max_fanout 10 [get_ports sign_w]
set_max_fanout 10 [get_ports {exp_w[3]}]
set_max_fanout 10 [get_ports {exp_w[2]}]
set_max_fanout 10 [get_ports {exp_w[1]}]
set_max_fanout 10 [get_ports {exp_w[0]}]
set_max_fanout 10 [get_ports {man_w[2]}]
set_max_fanout 10 [get_ports {man_w[1]}]
set_max_fanout 10 [get_ports {man_w[0]}]
set_max_transition 3 [get_ports sign_a]
set_max_transition 3 [get_ports {exp_a[3]}]
set_max_transition 3 [get_ports {exp_a[2]}]
set_max_transition 3 [get_ports {exp_a[1]}]
set_max_transition 3 [get_ports {exp_a[0]}]
set_max_transition 3 [get_ports {man_a[2]}]
set_max_transition 3 [get_ports {man_a[1]}]
set_max_transition 3 [get_ports {man_a[0]}]
set_max_transition 3 [get_ports sign_w]
set_max_transition 3 [get_ports {exp_w[3]}]
set_max_transition 3 [get_ports {exp_w[2]}]
set_max_transition 3 [get_ports {exp_w[1]}]
set_max_transition 3 [get_ports {exp_w[0]}]
set_max_transition 3 [get_ports {man_w[2]}]
set_max_transition 3 [get_ports {man_w[1]}]
set_max_transition 3 [get_ports {man_w[0]}]
set_input_transition -max 0.5  [get_ports sign_a]
set_input_transition -min 0.5  [get_ports sign_a]
set_input_transition -max 0.5  [get_ports {exp_a[3]}]
set_input_transition -min 0.5  [get_ports {exp_a[3]}]
set_input_transition -max 0.5  [get_ports {exp_a[2]}]
set_input_transition -min 0.5  [get_ports {exp_a[2]}]
set_input_transition -max 0.5  [get_ports {exp_a[1]}]
set_input_transition -min 0.5  [get_ports {exp_a[1]}]
set_input_transition -max 0.5  [get_ports {exp_a[0]}]
set_input_transition -min 0.5  [get_ports {exp_a[0]}]
set_input_transition -max 0.5  [get_ports {man_a[2]}]
set_input_transition -min 0.5  [get_ports {man_a[2]}]
set_input_transition -max 0.5  [get_ports {man_a[1]}]
set_input_transition -min 0.5  [get_ports {man_a[1]}]
set_input_transition -max 0.5  [get_ports {man_a[0]}]
set_input_transition -min 0.5  [get_ports {man_a[0]}]
set_input_transition -max 0.5  [get_ports sign_w]
set_input_transition -min 0.5  [get_ports sign_w]
set_input_transition -max 0.5  [get_ports {exp_w[3]}]
set_input_transition -min 0.5  [get_ports {exp_w[3]}]
set_input_transition -max 0.5  [get_ports {exp_w[2]}]
set_input_transition -min 0.5  [get_ports {exp_w[2]}]
set_input_transition -max 0.5  [get_ports {exp_w[1]}]
set_input_transition -min 0.5  [get_ports {exp_w[1]}]
set_input_transition -max 0.5  [get_ports {exp_w[0]}]
set_input_transition -min 0.5  [get_ports {exp_w[0]}]
set_input_transition -max 0.5  [get_ports {man_w[2]}]
set_input_transition -min 0.5  [get_ports {man_w[2]}]
set_input_transition -max 0.5  [get_ports {man_w[1]}]
set_input_transition -min 0.5  [get_ports {man_w[1]}]
set_input_transition -max 0.5  [get_ports {man_w[0]}]
set_input_transition -min 0.5  [get_ports {man_w[0]}]
