###################################################################

# Created by write_sdc on Sat May 23 16:14:52 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_wire_load_model -name Small -library                                       \
sc9_cln40g_base_rvt_tt_typical_max_0p90v_25c
set_load -pin_load 0.05 [get_ports adder_sign]
set_load -pin_load 0.05 [get_ports {adder_mant[27]}]
set_load -pin_load 0.05 [get_ports {adder_mant[26]}]
set_load -pin_load 0.05 [get_ports {adder_mant[25]}]
set_load -pin_load 0.05 [get_ports {adder_mant[24]}]
set_load -pin_load 0.05 [get_ports {adder_mant[23]}]
set_load -pin_load 0.05 [get_ports {adder_mant[22]}]
set_load -pin_load 0.05 [get_ports {adder_mant[21]}]
set_load -pin_load 0.05 [get_ports {adder_mant[20]}]
set_load -pin_load 0.05 [get_ports {adder_mant[19]}]
set_load -pin_load 0.05 [get_ports {adder_mant[18]}]
set_load -pin_load 0.05 [get_ports {adder_mant[17]}]
set_load -pin_load 0.05 [get_ports {adder_mant[16]}]
set_load -pin_load 0.05 [get_ports {adder_mant[15]}]
set_load -pin_load 0.05 [get_ports {adder_mant[14]}]
set_load -pin_load 0.05 [get_ports {adder_mant[13]}]
set_load -pin_load 0.05 [get_ports {adder_mant[12]}]
set_load -pin_load 0.05 [get_ports {adder_mant[11]}]
set_load -pin_load 0.05 [get_ports {adder_mant[10]}]
set_load -pin_load 0.05 [get_ports {adder_mant[9]}]
set_load -pin_load 0.05 [get_ports {adder_mant[8]}]
set_load -pin_load 0.05 [get_ports {adder_mant[7]}]
set_load -pin_load 0.05 [get_ports {adder_mant[6]}]
set_load -pin_load 0.05 [get_ports {adder_mant[5]}]
set_load -pin_load 0.05 [get_ports {adder_mant[4]}]
set_load -pin_load 0.05 [get_ports {adder_mant[3]}]
set_load -pin_load 0.05 [get_ports {adder_mant[2]}]
set_load -pin_load 0.05 [get_ports {adder_mant[1]}]
set_load -pin_load 0.05 [get_ports {adder_mant[0]}]
set_load -pin_load 0.05 [get_ports {adder_exp[9]}]
set_load -pin_load 0.05 [get_ports {adder_exp[8]}]
set_load -pin_load 0.05 [get_ports {adder_exp[7]}]
set_load -pin_load 0.05 [get_ports {adder_exp[6]}]
set_load -pin_load 0.05 [get_ports {adder_exp[5]}]
set_load -pin_load 0.05 [get_ports {adder_exp[4]}]
set_load -pin_load 0.05 [get_ports {adder_exp[3]}]
set_load -pin_load 0.05 [get_ports {adder_exp[2]}]
set_load -pin_load 0.05 [get_ports {adder_exp[1]}]
set_load -pin_load 0.05 [get_ports {adder_exp[0]}]
set_max_capacitance 0.15 [get_ports clk]
set_max_capacitance 0.15 [get_ports rst_n]
set_max_capacitance 0.15 [get_ports acc_clear]
set_max_capacitance 0.15 [get_ports sign_a]
set_max_capacitance 0.15 [get_ports {exp_a[3]}]
set_max_capacitance 0.15 [get_ports {exp_a[2]}]
set_max_capacitance 0.15 [get_ports {exp_a[1]}]
set_max_capacitance 0.15 [get_ports {exp_a[0]}]
set_max_capacitance 0.15 [get_ports {man_a[2]}]
set_max_capacitance 0.15 [get_ports {man_a[1]}]
set_max_capacitance 0.15 [get_ports {man_a[0]}]
set_max_capacitance 0.15 [get_ports sign_b]
set_max_capacitance 0.15 [get_ports {exp_b[3]}]
set_max_capacitance 0.15 [get_ports {exp_b[2]}]
set_max_capacitance 0.15 [get_ports {exp_b[1]}]
set_max_capacitance 0.15 [get_ports {exp_b[0]}]
set_max_capacitance 0.15 [get_ports {man_b[2]}]
set_max_capacitance 0.15 [get_ports {man_b[1]}]
set_max_capacitance 0.15 [get_ports {man_b[0]}]
set_max_capacitance 0.15 [get_ports norm_sign]
set_max_capacitance 0.15 [get_ports {norm_exp[9]}]
set_max_capacitance 0.15 [get_ports {norm_exp[8]}]
set_max_capacitance 0.15 [get_ports {norm_exp[7]}]
set_max_capacitance 0.15 [get_ports {norm_exp[6]}]
set_max_capacitance 0.15 [get_ports {norm_exp[5]}]
set_max_capacitance 0.15 [get_ports {norm_exp[4]}]
set_max_capacitance 0.15 [get_ports {norm_exp[3]}]
set_max_capacitance 0.15 [get_ports {norm_exp[2]}]
set_max_capacitance 0.15 [get_ports {norm_exp[1]}]
set_max_capacitance 0.15 [get_ports {norm_exp[0]}]
set_max_capacitance 0.15 [get_ports {norm_mant[23]}]
set_max_capacitance 0.15 [get_ports {norm_mant[22]}]
set_max_capacitance 0.15 [get_ports {norm_mant[21]}]
set_max_capacitance 0.15 [get_ports {norm_mant[20]}]
set_max_capacitance 0.15 [get_ports {norm_mant[19]}]
set_max_capacitance 0.15 [get_ports {norm_mant[18]}]
set_max_capacitance 0.15 [get_ports {norm_mant[17]}]
set_max_capacitance 0.15 [get_ports {norm_mant[16]}]
set_max_capacitance 0.15 [get_ports {norm_mant[15]}]
set_max_capacitance 0.15 [get_ports {norm_mant[14]}]
set_max_capacitance 0.15 [get_ports {norm_mant[13]}]
set_max_capacitance 0.15 [get_ports {norm_mant[12]}]
set_max_capacitance 0.15 [get_ports {norm_mant[11]}]
set_max_capacitance 0.15 [get_ports {norm_mant[10]}]
set_max_capacitance 0.15 [get_ports {norm_mant[9]}]
set_max_capacitance 0.15 [get_ports {norm_mant[8]}]
set_max_capacitance 0.15 [get_ports {norm_mant[7]}]
set_max_capacitance 0.15 [get_ports {norm_mant[6]}]
set_max_capacitance 0.15 [get_ports {norm_mant[5]}]
set_max_capacitance 0.15 [get_ports {norm_mant[4]}]
set_max_capacitance 0.15 [get_ports {norm_mant[3]}]
set_max_capacitance 0.15 [get_ports {norm_mant[2]}]
set_max_capacitance 0.15 [get_ports {norm_mant[1]}]
set_max_capacitance 0.15 [get_ports {norm_mant[0]}]
set_max_capacitance 0.15 [get_ports is_nan_input]
set_max_fanout 10 [get_ports clk]
set_max_fanout 10 [get_ports rst_n]
set_max_fanout 10 [get_ports acc_clear]
set_max_fanout 10 [get_ports sign_a]
set_max_fanout 10 [get_ports {exp_a[3]}]
set_max_fanout 10 [get_ports {exp_a[2]}]
set_max_fanout 10 [get_ports {exp_a[1]}]
set_max_fanout 10 [get_ports {exp_a[0]}]
set_max_fanout 10 [get_ports {man_a[2]}]
set_max_fanout 10 [get_ports {man_a[1]}]
set_max_fanout 10 [get_ports {man_a[0]}]
set_max_fanout 10 [get_ports sign_b]
set_max_fanout 10 [get_ports {exp_b[3]}]
set_max_fanout 10 [get_ports {exp_b[2]}]
set_max_fanout 10 [get_ports {exp_b[1]}]
set_max_fanout 10 [get_ports {exp_b[0]}]
set_max_fanout 10 [get_ports {man_b[2]}]
set_max_fanout 10 [get_ports {man_b[1]}]
set_max_fanout 10 [get_ports {man_b[0]}]
set_max_fanout 10 [get_ports norm_sign]
set_max_fanout 10 [get_ports {norm_exp[9]}]
set_max_fanout 10 [get_ports {norm_exp[8]}]
set_max_fanout 10 [get_ports {norm_exp[7]}]
set_max_fanout 10 [get_ports {norm_exp[6]}]
set_max_fanout 10 [get_ports {norm_exp[5]}]
set_max_fanout 10 [get_ports {norm_exp[4]}]
set_max_fanout 10 [get_ports {norm_exp[3]}]
set_max_fanout 10 [get_ports {norm_exp[2]}]
set_max_fanout 10 [get_ports {norm_exp[1]}]
set_max_fanout 10 [get_ports {norm_exp[0]}]
set_max_fanout 10 [get_ports {norm_mant[23]}]
set_max_fanout 10 [get_ports {norm_mant[22]}]
set_max_fanout 10 [get_ports {norm_mant[21]}]
set_max_fanout 10 [get_ports {norm_mant[20]}]
set_max_fanout 10 [get_ports {norm_mant[19]}]
set_max_fanout 10 [get_ports {norm_mant[18]}]
set_max_fanout 10 [get_ports {norm_mant[17]}]
set_max_fanout 10 [get_ports {norm_mant[16]}]
set_max_fanout 10 [get_ports {norm_mant[15]}]
set_max_fanout 10 [get_ports {norm_mant[14]}]
set_max_fanout 10 [get_ports {norm_mant[13]}]
set_max_fanout 10 [get_ports {norm_mant[12]}]
set_max_fanout 10 [get_ports {norm_mant[11]}]
set_max_fanout 10 [get_ports {norm_mant[10]}]
set_max_fanout 10 [get_ports {norm_mant[9]}]
set_max_fanout 10 [get_ports {norm_mant[8]}]
set_max_fanout 10 [get_ports {norm_mant[7]}]
set_max_fanout 10 [get_ports {norm_mant[6]}]
set_max_fanout 10 [get_ports {norm_mant[5]}]
set_max_fanout 10 [get_ports {norm_mant[4]}]
set_max_fanout 10 [get_ports {norm_mant[3]}]
set_max_fanout 10 [get_ports {norm_mant[2]}]
set_max_fanout 10 [get_ports {norm_mant[1]}]
set_max_fanout 10 [get_ports {norm_mant[0]}]
set_max_fanout 10 [get_ports is_nan_input]
set_max_transition 3 [get_ports clk]
set_max_transition 3 [get_ports rst_n]
set_max_transition 3 [get_ports acc_clear]
set_max_transition 3 [get_ports sign_a]
set_max_transition 3 [get_ports {exp_a[3]}]
set_max_transition 3 [get_ports {exp_a[2]}]
set_max_transition 3 [get_ports {exp_a[1]}]
set_max_transition 3 [get_ports {exp_a[0]}]
set_max_transition 3 [get_ports {man_a[2]}]
set_max_transition 3 [get_ports {man_a[1]}]
set_max_transition 3 [get_ports {man_a[0]}]
set_max_transition 3 [get_ports sign_b]
set_max_transition 3 [get_ports {exp_b[3]}]
set_max_transition 3 [get_ports {exp_b[2]}]
set_max_transition 3 [get_ports {exp_b[1]}]
set_max_transition 3 [get_ports {exp_b[0]}]
set_max_transition 3 [get_ports {man_b[2]}]
set_max_transition 3 [get_ports {man_b[1]}]
set_max_transition 3 [get_ports {man_b[0]}]
set_max_transition 3 [get_ports norm_sign]
set_max_transition 3 [get_ports {norm_exp[9]}]
set_max_transition 3 [get_ports {norm_exp[8]}]
set_max_transition 3 [get_ports {norm_exp[7]}]
set_max_transition 3 [get_ports {norm_exp[6]}]
set_max_transition 3 [get_ports {norm_exp[5]}]
set_max_transition 3 [get_ports {norm_exp[4]}]
set_max_transition 3 [get_ports {norm_exp[3]}]
set_max_transition 3 [get_ports {norm_exp[2]}]
set_max_transition 3 [get_ports {norm_exp[1]}]
set_max_transition 3 [get_ports {norm_exp[0]}]
set_max_transition 3 [get_ports {norm_mant[23]}]
set_max_transition 3 [get_ports {norm_mant[22]}]
set_max_transition 3 [get_ports {norm_mant[21]}]
set_max_transition 3 [get_ports {norm_mant[20]}]
set_max_transition 3 [get_ports {norm_mant[19]}]
set_max_transition 3 [get_ports {norm_mant[18]}]
set_max_transition 3 [get_ports {norm_mant[17]}]
set_max_transition 3 [get_ports {norm_mant[16]}]
set_max_transition 3 [get_ports {norm_mant[15]}]
set_max_transition 3 [get_ports {norm_mant[14]}]
set_max_transition 3 [get_ports {norm_mant[13]}]
set_max_transition 3 [get_ports {norm_mant[12]}]
set_max_transition 3 [get_ports {norm_mant[11]}]
set_max_transition 3 [get_ports {norm_mant[10]}]
set_max_transition 3 [get_ports {norm_mant[9]}]
set_max_transition 3 [get_ports {norm_mant[8]}]
set_max_transition 3 [get_ports {norm_mant[7]}]
set_max_transition 3 [get_ports {norm_mant[6]}]
set_max_transition 3 [get_ports {norm_mant[5]}]
set_max_transition 3 [get_ports {norm_mant[4]}]
set_max_transition 3 [get_ports {norm_mant[3]}]
set_max_transition 3 [get_ports {norm_mant[2]}]
set_max_transition 3 [get_ports {norm_mant[1]}]
set_max_transition 3 [get_ports {norm_mant[0]}]
set_max_transition 3 [get_ports is_nan_input]
create_clock [get_ports clk]  -period 2.5  -waveform {0 1.25}
set_clock_uncertainty 0.1  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  -max 0.25  [get_ports acc_clear]
set_input_delay -clock clk  -min 0  [get_ports acc_clear]
set_input_delay -clock clk  -max 0.25  [get_ports sign_a]
set_input_delay -clock clk  -min 0  [get_ports sign_a]
set_input_delay -clock clk  -max 0.25  [get_ports {exp_a[3]}]
set_input_delay -clock clk  -min 0  [get_ports {exp_a[3]}]
set_input_delay -clock clk  -max 0.25  [get_ports {exp_a[2]}]
set_input_delay -clock clk  -min 0  [get_ports {exp_a[2]}]
set_input_delay -clock clk  -max 0.25  [get_ports {exp_a[1]}]
set_input_delay -clock clk  -min 0  [get_ports {exp_a[1]}]
set_input_delay -clock clk  -max 0.25  [get_ports {exp_a[0]}]
set_input_delay -clock clk  -min 0  [get_ports {exp_a[0]}]
set_input_delay -clock clk  -max 0.25  [get_ports {man_a[2]}]
set_input_delay -clock clk  -min 0  [get_ports {man_a[2]}]
set_input_delay -clock clk  -max 0.25  [get_ports {man_a[1]}]
set_input_delay -clock clk  -min 0  [get_ports {man_a[1]}]
set_input_delay -clock clk  -max 0.25  [get_ports {man_a[0]}]
set_input_delay -clock clk  -min 0  [get_ports {man_a[0]}]
set_input_delay -clock clk  -max 0.25  [get_ports sign_b]
set_input_delay -clock clk  -min 0  [get_ports sign_b]
set_input_delay -clock clk  -max 0.25  [get_ports {exp_b[3]}]
set_input_delay -clock clk  -min 0  [get_ports {exp_b[3]}]
set_input_delay -clock clk  -max 0.25  [get_ports {exp_b[2]}]
set_input_delay -clock clk  -min 0  [get_ports {exp_b[2]}]
set_input_delay -clock clk  -max 0.25  [get_ports {exp_b[1]}]
set_input_delay -clock clk  -min 0  [get_ports {exp_b[1]}]
set_input_delay -clock clk  -max 0.25  [get_ports {exp_b[0]}]
set_input_delay -clock clk  -min 0  [get_ports {exp_b[0]}]
set_input_delay -clock clk  -max 0.25  [get_ports {man_b[2]}]
set_input_delay -clock clk  -min 0  [get_ports {man_b[2]}]
set_input_delay -clock clk  -max 0.25  [get_ports {man_b[1]}]
set_input_delay -clock clk  -min 0  [get_ports {man_b[1]}]
set_input_delay -clock clk  -max 0.25  [get_ports {man_b[0]}]
set_input_delay -clock clk  -min 0  [get_ports {man_b[0]}]
set_input_delay -clock clk  -max 0.25  [get_ports norm_sign]
set_input_delay -clock clk  -min 0  [get_ports norm_sign]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_exp[9]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_exp[9]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_exp[8]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_exp[8]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_exp[7]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_exp[7]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_exp[6]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_exp[6]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_exp[5]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_exp[5]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_exp[4]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_exp[4]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_exp[3]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_exp[3]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_exp[2]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_exp[2]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_exp[1]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_exp[1]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_exp[0]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_exp[0]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[23]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[23]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[22]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[22]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[21]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[21]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[20]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[20]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[19]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[19]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[18]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[18]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[17]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[17]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[16]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[16]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[15]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[15]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[14]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[14]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[13]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[13]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[12]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[12]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[11]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[11]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[10]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[10]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[9]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[9]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[8]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[8]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[7]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[7]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[6]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[6]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[5]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[5]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[4]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[4]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[3]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[3]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[2]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[2]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[1]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[1]}]
set_input_delay -clock clk  -max 0.25  [get_ports {norm_mant[0]}]
set_input_delay -clock clk  -min 0  [get_ports {norm_mant[0]}]
set_input_delay -clock clk  -max 0.25  [get_ports is_nan_input]
set_input_delay -clock clk  -min 0  [get_ports is_nan_input]
set_output_delay -clock clk  -max 0.25  [get_ports adder_sign]
set_output_delay -clock clk  -min 0  [get_ports adder_sign]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[27]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[27]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[26]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[26]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[25]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[25]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[24]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[24]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[23]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[23]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[22]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[22]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[21]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[21]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[20]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[20]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[19]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[19]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[18]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[18]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[17]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[17]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[16]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[16]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[15]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[15]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[14]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[14]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[13]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[13]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[12]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[12]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[11]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[11]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[10]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[10]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[9]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[9]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[8]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[8]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[7]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[7]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[6]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[6]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[5]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[5]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[4]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[4]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[3]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[3]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[2]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[2]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[1]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[1]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_mant[0]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_mant[0]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_exp[9]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_exp[9]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_exp[8]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_exp[8]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_exp[7]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_exp[7]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_exp[6]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_exp[6]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_exp[5]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_exp[5]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_exp[4]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_exp[4]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_exp[3]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_exp[3]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_exp[2]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_exp[2]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_exp[1]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_exp[1]}]
set_output_delay -clock clk  -max 0.25  [get_ports {adder_exp[0]}]
set_output_delay -clock clk  -min 0  [get_ports {adder_exp[0]}]
set_input_transition -max 0.5  [get_ports clk]
set_input_transition -min 0.5  [get_ports clk]
set_input_transition -max 0.5  [get_ports rst_n]
set_input_transition -min 0.5  [get_ports rst_n]
set_input_transition -max 0.5  [get_ports acc_clear]
set_input_transition -min 0.5  [get_ports acc_clear]
set_input_transition -max 0.5  [get_ports sign_a]
set_input_transition -min 0.5  [get_ports sign_a]
set_input_transition -max 0.5  [get_ports {exp_a[3]}]
set_input_transition -min 0.5  [get_ports {exp_a[3]}]
set_input_transition -max 0.5  [get_ports {exp_a[2]}]
set_input_transition -min 0.5  [get_ports {exp_a[2]}]
set_input_transition -max 0.5  [get_ports {exp_a[1]}]
set_input_transition -min 0.5  [get_ports {exp_a[1]}]
set_input_transition -max 0.5  [get_ports {exp_a[0]}]
set_input_transition -min 0.5  [get_ports {exp_a[0]}]
set_input_transition -max 0.5  [get_ports {man_a[2]}]
set_input_transition -min 0.5  [get_ports {man_a[2]}]
set_input_transition -max 0.5  [get_ports {man_a[1]}]
set_input_transition -min 0.5  [get_ports {man_a[1]}]
set_input_transition -max 0.5  [get_ports {man_a[0]}]
set_input_transition -min 0.5  [get_ports {man_a[0]}]
set_input_transition -max 0.5  [get_ports sign_b]
set_input_transition -min 0.5  [get_ports sign_b]
set_input_transition -max 0.5  [get_ports {exp_b[3]}]
set_input_transition -min 0.5  [get_ports {exp_b[3]}]
set_input_transition -max 0.5  [get_ports {exp_b[2]}]
set_input_transition -min 0.5  [get_ports {exp_b[2]}]
set_input_transition -max 0.5  [get_ports {exp_b[1]}]
set_input_transition -min 0.5  [get_ports {exp_b[1]}]
set_input_transition -max 0.5  [get_ports {exp_b[0]}]
set_input_transition -min 0.5  [get_ports {exp_b[0]}]
set_input_transition -max 0.5  [get_ports {man_b[2]}]
set_input_transition -min 0.5  [get_ports {man_b[2]}]
set_input_transition -max 0.5  [get_ports {man_b[1]}]
set_input_transition -min 0.5  [get_ports {man_b[1]}]
set_input_transition -max 0.5  [get_ports {man_b[0]}]
set_input_transition -min 0.5  [get_ports {man_b[0]}]
set_input_transition -max 0.5  [get_ports norm_sign]
set_input_transition -min 0.5  [get_ports norm_sign]
set_input_transition -max 0.5  [get_ports {norm_exp[9]}]
set_input_transition -min 0.5  [get_ports {norm_exp[9]}]
set_input_transition -max 0.5  [get_ports {norm_exp[8]}]
set_input_transition -min 0.5  [get_ports {norm_exp[8]}]
set_input_transition -max 0.5  [get_ports {norm_exp[7]}]
set_input_transition -min 0.5  [get_ports {norm_exp[7]}]
set_input_transition -max 0.5  [get_ports {norm_exp[6]}]
set_input_transition -min 0.5  [get_ports {norm_exp[6]}]
set_input_transition -max 0.5  [get_ports {norm_exp[5]}]
set_input_transition -min 0.5  [get_ports {norm_exp[5]}]
set_input_transition -max 0.5  [get_ports {norm_exp[4]}]
set_input_transition -min 0.5  [get_ports {norm_exp[4]}]
set_input_transition -max 0.5  [get_ports {norm_exp[3]}]
set_input_transition -min 0.5  [get_ports {norm_exp[3]}]
set_input_transition -max 0.5  [get_ports {norm_exp[2]}]
set_input_transition -min 0.5  [get_ports {norm_exp[2]}]
set_input_transition -max 0.5  [get_ports {norm_exp[1]}]
set_input_transition -min 0.5  [get_ports {norm_exp[1]}]
set_input_transition -max 0.5  [get_ports {norm_exp[0]}]
set_input_transition -min 0.5  [get_ports {norm_exp[0]}]
set_input_transition -max 0.5  [get_ports {norm_mant[23]}]
set_input_transition -min 0.5  [get_ports {norm_mant[23]}]
set_input_transition -max 0.5  [get_ports {norm_mant[22]}]
set_input_transition -min 0.5  [get_ports {norm_mant[22]}]
set_input_transition -max 0.5  [get_ports {norm_mant[21]}]
set_input_transition -min 0.5  [get_ports {norm_mant[21]}]
set_input_transition -max 0.5  [get_ports {norm_mant[20]}]
set_input_transition -min 0.5  [get_ports {norm_mant[20]}]
set_input_transition -max 0.5  [get_ports {norm_mant[19]}]
set_input_transition -min 0.5  [get_ports {norm_mant[19]}]
set_input_transition -max 0.5  [get_ports {norm_mant[18]}]
set_input_transition -min 0.5  [get_ports {norm_mant[18]}]
set_input_transition -max 0.5  [get_ports {norm_mant[17]}]
set_input_transition -min 0.5  [get_ports {norm_mant[17]}]
set_input_transition -max 0.5  [get_ports {norm_mant[16]}]
set_input_transition -min 0.5  [get_ports {norm_mant[16]}]
set_input_transition -max 0.5  [get_ports {norm_mant[15]}]
set_input_transition -min 0.5  [get_ports {norm_mant[15]}]
set_input_transition -max 0.5  [get_ports {norm_mant[14]}]
set_input_transition -min 0.5  [get_ports {norm_mant[14]}]
set_input_transition -max 0.5  [get_ports {norm_mant[13]}]
set_input_transition -min 0.5  [get_ports {norm_mant[13]}]
set_input_transition -max 0.5  [get_ports {norm_mant[12]}]
set_input_transition -min 0.5  [get_ports {norm_mant[12]}]
set_input_transition -max 0.5  [get_ports {norm_mant[11]}]
set_input_transition -min 0.5  [get_ports {norm_mant[11]}]
set_input_transition -max 0.5  [get_ports {norm_mant[10]}]
set_input_transition -min 0.5  [get_ports {norm_mant[10]}]
set_input_transition -max 0.5  [get_ports {norm_mant[9]}]
set_input_transition -min 0.5  [get_ports {norm_mant[9]}]
set_input_transition -max 0.5  [get_ports {norm_mant[8]}]
set_input_transition -min 0.5  [get_ports {norm_mant[8]}]
set_input_transition -max 0.5  [get_ports {norm_mant[7]}]
set_input_transition -min 0.5  [get_ports {norm_mant[7]}]
set_input_transition -max 0.5  [get_ports {norm_mant[6]}]
set_input_transition -min 0.5  [get_ports {norm_mant[6]}]
set_input_transition -max 0.5  [get_ports {norm_mant[5]}]
set_input_transition -min 0.5  [get_ports {norm_mant[5]}]
set_input_transition -max 0.5  [get_ports {norm_mant[4]}]
set_input_transition -min 0.5  [get_ports {norm_mant[4]}]
set_input_transition -max 0.5  [get_ports {norm_mant[3]}]
set_input_transition -min 0.5  [get_ports {norm_mant[3]}]
set_input_transition -max 0.5  [get_ports {norm_mant[2]}]
set_input_transition -min 0.5  [get_ports {norm_mant[2]}]
set_input_transition -max 0.5  [get_ports {norm_mant[1]}]
set_input_transition -min 0.5  [get_ports {norm_mant[1]}]
set_input_transition -max 0.5  [get_ports {norm_mant[0]}]
set_input_transition -min 0.5  [get_ports {norm_mant[0]}]
set_input_transition -max 0.5  [get_ports is_nan_input]
set_input_transition -min 0.5  [get_ports is_nan_input]
